import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/ui/header'
import { AuthProvider } from '@/providers/auth'
import { Footer } from '@/components/ui/footer'
import CartProvider from '@/providers/cart'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const DynamicContextProvider = dynamic(() => import('@/providers/cart').then(mod => mod.default), {
  ssr: false
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex h-full flex-col'>
          <AuthProvider>
            <DynamicContextProvider>
              <Header />
              <main className='flex-1'>
                {children}
              </main>
              <Footer />
            </DynamicContextProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
